<?php
/** 
* @file
*Implementing hook function to generate a simple newsletter
*/
use \Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mail().
 */
function ednet_newsletter_cron_mail($key, &$message, $params) {
    $options = array(
      'langcode' => $message['langcode'],
    );
  
    switch ($key) {
      case 'create_article':
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = t('@title', array('@title' => $params['node_title']), $options);
        $message['body'][] = $params['message'];
        break;
    }
  }
  
  /**
   * Implements hook_entity_insert().
   */
  function ednet_newsletter_cron_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  
    if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'simplenews_issue')) {
      return;
    }
  
    $mailManager = \Drupal::service('plugin.manager.mail');
  
    $module = 'ednet_newsletter_cron';
    $key = 'create_article';
    //$to = 'EDNETDEV@Victoria1.gov.bc.ca';
    $to = 'EDNETDL@Victoria1.gov.bc.ca';
    $params['message'] = $entity->get('body')->value;
    $params['node_title'] = $entity->label();
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
  
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
    if ($result['result'] !== true) {
      drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
    }
    else {
      drupal_set_message(t('Your message has been sent.'));
    }
  
}

function ednet_newsletter_cron_cron() {
    $dispalyDateToday = date('l, M d, Y');
    $highlightQuery = "SELECT nid, title, field_highlight_summary_value, DATE(FROM_UNIXTIME(created)) as created FROM node__field_highlight_summary,node_field_data WHERE node__field_highlight_summary.entity_id = node_field_data.nid AND node_field_data.promote = 1 ORDER BY created DESC";
    // $staffPostQurey = "SELECT nid, title, DATE_FORMAT(FROM_UNIXTIME(created), '%y %M %D %r') as created FROM node_field_data WHERE DATE(FROM_UNIXTIME(created)) BETWEEN DATE_SUB( NOW( ) , INTERVAL 2 DAY ) AND CURDATE( ) AND type = 'article'";
    if(date('D') == 'Mon') { 
        $staffPostQurey = "SELECT nid, title, DATE_FORMAT(FROM_UNIXTIME(created), '%M %D %r') as created FROM node_field_data WHERE DATE(FROM_UNIXTIME(created)) >= NOW() - INTERVAL 3 DAY AND type = 'article' AND status = 1";
    } else {
        $staffPostQurey = "SELECT nid, title, DATE_FORMAT(FROM_UNIXTIME(created), '%M %D %r') as created FROM node_field_data WHERE DATE(FROM_UNIXTIME(created)) >= NOW() - INTERVAL 1 DAY AND type = 'article'AND status = 1";
    }
    $eventsQuery = "SELECT nid, title, DATE_FORMAT(node_revision__field_event_start_date.field_event_start_date_value, '%M %D at %T') as event_start_date FROM node_field_data, node_revision__field_event_start_date WHERE node_revision__field_event_start_date.entity_id = node_field_data.nid AND field_event_start_date_value >= DATE(NOW()) AND field_event_start_date_value <= (DATE(NOW()) + INTERVAL 7 DAY)";
    $database = \Drupal::database();
    $query2 = $database->query($highlightQuery);
    $query = $database->query($staffPostQurey);
    $query3 = $database->query($eventsQuery);
    $staffPostsResults = $query->fetchAll();
    $highlightsResults = $query2->fetchAll();
    $eventsResults = $query3->fetchAll();
    $i = 0;
    $j = 0;
    $k = 0;
    //Loop for getting the Highlights 
    foreach ($highlightsResults as $highlightsResult) {
        $i++;
        $highlightsOutput .= "<tr style='padding-bottom: 30px; border-style:none;'>
        <td style='font-family: arial; width:10%; color: white; font-size: 11pt;vertical-align: top; border-style:none;'>
        <span style='font-family: arial !important; !important; font-weight: bold;'></span><br />
        </td>
        <td style='width:80%'>
            <table>
                <tr>
                <td style='width: 50px; vertical-align:top; padding-top: 10px'><div style='border:1px solid #666; color:white; font-size: 14pt; background: #ff680d; height: 40px; width:40px; text-align:center'>$i</div></td>
                    <td style='padding-left:15px;'>
                        <span
                            style='
                            font-family: arial !important;
                            color: #333;
                            font-size: 14pt;
                            font-weight: bold;
                            text-decoration: none;
                            '
                            ><a style='color: #000; text-decoration:none;' href='http://gww.bcedintra.gov.bc.ca/node/$highlightsResult->nid'>$highlightsResult->title</a></span>
                        <br />  <span
                        style='
                            font-family: arial !important;
                            color: #333;
                            font-size: 12pt;
                            text-decoration: none;
                        
                        '
                        >$highlightsResult->field_highlight_summary_value </span>
                    </td>
                </tr>
            </table>
        </td>
        <td style='width: 10%'></td>
      </tr>";
    }
    //Loop for getting the Staff Posts 

    foreach ($staffPostsResults as $staffPostsResult) {
        $j++;
        $staffPostsOutput .= "<tr style='padding-bottom: 15px; padding-top:15px; border-style:none;'>
        <td style='width: 10%'></td>
        <td style='width: 80%; font-family: arial;vertical-align: top; border-bottom: 1px solid #ccc; padding-left: 65px;'>
        <span
            style='
                font-family: arial !important;
                color: #333;
                font-size: 12pt;
                font-weight: bold;
                text-decoration: none;
            '
        >
            <a style='color: #000; text-decoration:none; padding-bottom: 10px' href='http://gww.bcedintra.gov.bc.ca/node/$staffPostsResult->nid'>$staffPostsResult->title</a>
        </span>
        <br>
        <span
        style='
            font-family: arial !important;
            color: #333;
            text-decoration: none;
            width:100%;
            font-size: 12pt;
            margin-top:10px;
            padding-top:10px;
        '> $staffPostsResult->created </span>
        
            <span
            style='
                font-family: arial !important;
                color: #333;
                font-size: 10pt;
                text-decoration: none;
                margin-bottom: 10px;
            '>$staffPostsResult->field_highlight_summary_value</span> 
        </td>
        <td style='width: 10%'></td>
        </tr>";
    }
    if($j == 0){
        $staffPostsResults = "<tr><td colspan='3' style='text-align:center'>There are currently no new Staff Announcements. <a href='https://gww.bcedintra.gov.bc.ca/'>Add a staff announcement</a>.</td></tr>";
    }
    //Loop for getting the Events 
    foreach ($eventsResults as $eventsResult) {
        $k++;
        $eventsOutput .= "<tr><td style='padding-bottom: 10px; padding-top: 10px; border-bottom: 1px solid #ccc; width:100%; padding-left: 65px;'>
        <span
        style='
            font-family: arial !important;
            color: #333;
            font-size: 12pt;
            font-weight: bold;
            text-decoration: none;
            margin-bottom:15px;
        '
        >
            <a style='color:#000; text-decoration:none; font-size: 14pt' href='http://gww.bcedintra.gov.bc.ca/node/$eventsResult->nid'>$eventsResult->title</a>
        </span>
        <br/>
        <span
        style='
            font-family: arial !important;
            color: #333;
            font-size: 12pt;
            text-decoration: none;
            border-bottom: 1px solid #ccc;
            margin-bottom: 15px;
        '> $eventsResult->event_start_date </span>    
        </td></tr>";
    }
    $node = Node::create([
        'type'        => 'simplenews_issue',
        'title'       => 'Ednet Newsletter '. $dispalyDateToday,
        'body'        => ['value' => '
        <table style="width: 100%;">
            <tr>
                <td style="width:15%"> </td>
                <td style="width: 70%; background: #efefef;"> 
                    <!-- HEADER -->

                        <table  style="background-color: #ff680d; border-collapse: collapse; border-style: none; margin: 0px; border:none; border-spacing: 0; font-family:arial; width:100%;">
                            <tr style="margin: 0 auto;border-style: none;"> 
                                <td style="width: 10%;"></td>
                                <td style="border-style: none;background-color: #ff680d;font-family:arial;font-size:12pt;color:white; width:80%;">
                                    <table>
                                        <tr style="border-style: none;">
                                            <td style="vertical-align:center; width:560px; text-align:left; font-family:arial; color:white"><h1>EdNet Newsletter</h1></td>
                                            <td style="border-style: none;width:260px; font-family:arial; color:white; text-align:right; background-color: #ff680d;">' .  $dispalyDateToday .'</td> 	
                                        </tr>
                                    </table>
                                </td>
                                <td style="width: 10%;"></td>
                            </tr>
                        </tbody></table>


                    <!-- TOP STORIES -->

                        <table style="width:100%; background:#e9e9e9; border-bottom: 1px solid #ccc; border-top: 1px solid #ccc;">
                            <tr>
                                <td style="width: 10%;"></td>
                                <td style="width: 80%; padding: 15px 0;  color: #333; font-weight: bold; font-family:arial; font-size: 18pt; text-align:left;">Top Stories</td>
                                <td style="width: 10%"></td>
                            </tr>
                        </table>
                        <table style="width:100%;">' . $highlightsOutput . '</table>

                    <!-- STAFF ANNOUNCEMENTS -->
                        <table style="width:100%; background:#e9e9e9; border-bottom: 1px solid #ccc; border-top: 1px solid #ccc;">
                            <tr>
                                <td style="width: 10%"></td>
                                <td style="width: 80%; padding: 15px 0;  color: #333; font-weight: bold; font-family:arial; font-size: 14pt; text-align:left; ">Staff Announcements</td>
                                <td style="width: 10%"></td>
                            </tr>
                        </table>
                        <table style="width:100%;">'.  $staffPostsOutput . '</table>

                    <!-- UPCOMING MINISTRY EVENTS -->
                        <table style="width:100%; background:#e9e9e9; border-bottom: 1px solid #ccc; border-top: 1px solid #ccc;">
                            <tr>
                                <td style="width: 10%"></td>
                                <td style="width: 80%; padding: 15px 0; color: #333; font-weight: bold; font-family:arial; font-size: 14pt; text-align:left;">Upcoming Ministry Events</td>									
                                <td style="width: 10%"></td>
                            </tr>
                        </table>
                        <table style="width:100%;">
                            <tr>
                                <td style="width: 10%"></td>
                                <td style="width:80%;"><table style="width:100%">' . $eventsOutput . '</table></td>
                                <td style="width: 10%"></td>
                            </tr>      
                    </table>

                    <!-- FOOTER -->
                    <table style="width: 100%;">
                        <tr style="vertical-align"middle>
                            <td align="center" style="font-family:arial; font-size:10pt; background-color: #3e454c; color: #FFF; height: 200;>
                                <p style="font-family: arial;">EdNet Update is delivered fresh at 9am daily.</p>
                                <p style="font-family: arial;">This is an automated message. Please do NOT reply to the sender email.</p>
                                <p style="font-family: arial">If you are receiving this email and are not an employee of the Ministry of Education</p> 
                                <p style="font-family: arial">please send an email to <a href="mailto:educwebs@victoria1.gov.bc.ca" style="color:#ff680d">Web Services</a>.</p>
                            </td>
                        </tr>
                    </table>
                    <!-- END FOOTER -->
                </td>
                <td style="width:15%"> </td>
            </tr>
        </table>', 'format' => 'full_html'],
    ]);

    $node->save();
}