<?php
/** 
* @file
*Implementing hook function to generate a simple newsletter
*/
use \Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mail().
 */
function ednet_newsletter_cron_mail($key, &$message, $params) {
    $options = array(
      'langcode' => $message['langcode'],
    );
  
    switch ($key) {
      case 'create_article':
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = t('@title', array('@title' => $params['node_title']), $options);
        $message['body'][] = $params['message'];
        break;
    }
  }
  
  /**
   * Implements hook_entity_insert().
   */
  function ednet_newsletter_cron_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  
    if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'simplenews_issue')) {
      return;
    }
  
    $mailManager = \Drupal::service('plugin.manager.mail');
  
    $module = 'ednet_newsletter_cron';
    $key = 'create_article';
    $to = 'EDNETDEV@Victoria1.gov.bc.ca';
    $params['message'] = $entity->get('body')->value;
    $params['node_title'] = $entity->label();
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
  
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
    if ($result['result'] !== true) {
      drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
    }
    else {
      drupal_set_message(t('Your message has been sent.'));
    }
  
}

function ednet_newsletter_cron_cron() {
    $dispalyDateToday = date('l, M d, Y');
    $highlightQuery = "SELECT nid, title, field_highlight_summary_value, DATE(FROM_UNIXTIME(created)) as created FROM node__field_highlight_summary,node_field_data WHERE node__field_highlight_summary.entity_id = node_field_data.nid AND node_field_data.promote = 1";
    $staffPostQurey = "SELECT nid, title, DATE_FORMAT(FROM_UNIXTIME(created), '%y %M %D %r') as created FROM node_field_data WHERE DATE(FROM_UNIXTIME(created)) BETWEEN DATE_SUB( NOW( ) ,INTERVAL 1 DAY ) AND CURDATE( ) AND type = 'article'";
    $eventsQuery = "SELECT nid, title, node_revision__field_event_start_date.field_event_start_date_value as event_start_date FROM node_field_data, node_revision__field_event_start_date WHERE node_revision__field_event_start_date.entity_id = node_field_data.nid AND field_event_start_date_value >= (DATE(NOW()) - INTERVAL 7 DAY)";
    $database = \Drupal::database();
    $query2 = $database->query($highlightQuery);
    $query = $database->query($staffPostQurey);
    $query3 = $database->query($eventsQuery);
    $staffPostsResults = $query->fetchAll();
    $highlightsResults = $query2->fetchAll();
    $eventsResults = $query3->fetchAll();
    $i = 0;
    $j = 0;
    $k = 0;
    //Loop for getting the Highlights 
    foreach ($highlightsResults as $highlightsResult) {
        $i++;
        $highlightsOutput .= "<tr style='padding-bottom: 40px; border-style:none;'>
        <td colspan='2'style='font-family: arial;padding: 0 50px 0 25px;font-size: 11pt;vertical-align: top; border-style:none;'>
        <span style='font-family: arial !important; font-size: 22px !important; font-weight: bold;'>$i</span><br />
        <span
            style='
              font-family: arial !important;
              color: #333;
              font-size: 22px;
              font-weight: bold;
              text-decoration: none;
            '
            > <a href='http://dori.bcedintra.gov.bc.ca/$highlightsResult->nid'>$highlightsResult->title</a> </span>
          <br /> $highlightsResult->field_highlight_summary_value <br /><br />
        </td>
      </tr>";
    }
    //Loop for getting the Staff Posts 
    foreach ($staffPostsResults as $staffPostsResult) {
        $j++;
        $staffPostsOutput .= "<tr style='padding-bottom: 40px; border-style:none;'>
        <td colspan='2'style='background-color:#f5f5f5;font-family: arial;padding: 0 50px 0 25px;font-size: 11pt;vertical-align: top; border-style:none;'>
        
        <span
            style='
                font-family: arial !important;
                color: #333;
                font-size: 22px;
                font-weight: bold;
                text-decoration: none;
            '
            >$j. <a href='http://dori.bcedintra.gov.bc.ca/node/$staffPostsResult->nid'>$staffPostsResult->title</a> </span><br />
        <span
        style='
            font-family: arial !important;
            color: #333;
            font-size: 16px;
            text-decoration: none;
            padding-left: 26px;
        '> $staffPostsResult->created </span>    
            <br /> $staffPostsResult->field_highlight_summary_value <br /><br />
        </td>
        </tr>";
    }
    //Loop for getting the Events 
    foreach ($eventsResults as $eventsResult) {
        $k++;
        $eventsOutput .= "<tr style='padding-bottom: 40px; border-style:none;'>
        <td colspan='2'style='font-family: arial;padding: 0 50px 10px 25px;font-size: 11pt;vertical-align: top; border-style:none;'>
        
        <span
            style='
                font-family: arial !important;
                color: #333;
                font-size: 18px;
                font-weight: bold;
                text-decoration: none;
            '
            >$k) <a href='http://ednet-test-mod2.dd:8083/node/$eventsResult->nid'>$eventsResult->title</a> </span><br />
        <span
        style='
            font-family: arial !important;
            color: #333;
            font-size: 16px;
            text-decoration: none;
            padding-left: 26px;
        '> $eventsResult->event_start_date </span>    
        </td>
        </tr>";
    }
    $node = Node::create([
        'type'        => 'simplenews_issue',
        'title'       => 'Ednet Issue '. $dispalyDateToday,
        'body'        => ['value' => '<table bgcolor="#FFF" style="border-collapse: collapse; border-style: none; margin: 0px; border:none; border-spacing: 0; font-family:arial;">
        <!-- HEADER -->
        <tr style="margin: 0 auto;border-style: none;">
            <td style="border-style: none;background-color: #ff680d;font-family:arial;font-size:12pt;color:white; padding: 0px 50px 0px 50px">
                <table>
                    <tr style="background-color: #ff680d; border-style: none;">
                      <td style="vertical-align:center; padding:10px 0; width:560px; text-align:left; vertical-align:center; font-family:arial; color:white"><strong>MINISTRY NEWS</strong></td>
                      <td style="border-style: none;width:260px; font-family:arial; color:white; text-align:right; background-color: #ff680d;">' .  $dispalyDateToday .'</td> 	
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <!-- <table bgcolor="#FFF" style=" border-collapse: collapse; border-style: none;border:none; border-spacing: 0; font-family:arial; margin: 0px;">
        <tr style="margin: 0 auto; background-color: #FFF;">
            <td style="padding:0px"> -->
                <table style="width: 100%;">
                    <tr>
                        <td style="width: 50px;"></td>
                        <td style="padding: 15px 0;  color: #333; font-weight: bold; font-family:arial; font-size: 18pt; text-align:center; border-bottom: 1px solid #ccc;">Headlines</td>
                        <td style="width: 50px"></td>
                    </tr>
                </table>'
                . $highlightsOutput .
                '
                <table style="width:100%; background:#e9e9e9;">
                    <tr>
                        <td style="width: 50px"></td>
                        <td style="padding: 15px 0;  color: #333; font-weight: bold; font-family:arial; font-size: 18pt; text-align:center; border-bottom: 1px solid #ccc;">Staff Announcements</td>
                        <td style="width: 50px"></td>
                    </tr>
                </table>
                '.  $staffPostsOutput . '
                <table style="width:100%;">
                    <tr>
                        <td style="width: 50px"></td>
                        <td style=" color: #333; font-weight: bold; font-family:arial; font-size: 18pt; text-align:center; border-bottom: 1px solid #ccc; padding:20px">Upcoming Ministry Events</td>									
                        <td style="width: 50px"></td>
                    </tr>
                </table>
                <table style="padding: 0 50px; width:100%;">
                    <tr style="border-style: none;">
                        <td style="width: 100%;">
                            <table style="width:100%; border-style: none;" >
                                <tr>
                                    <td style="font-family: arial; font-size:11pt; width:200px; text-align:center;"><p>Upcoming in the next 7 days</p></td>
                                </tr>
                                <tr>
                                    <td style="font-family: arial; font-size:11pt; width:100%">' . $eventsOutput . '</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <!-- Footer -->
                <table style="width: 100%;">
                    <tr style="height:200px;">
                        <td align="center" style="font-family:arial; font-size:10pt; background-color: #3e454c; color: #FFF; height: 250px; padding: 50px 50px;" valign="top">
                            <table>
                                <tr>
                                    <td style="color:white">
                                        <p style="font-family: arial;">EdNet Update is delivered fresh at 9am daily.</p>
                                        <p style="font-family: arial;">This is an automated message. Please do NOT reply to the sender email.</p>
                                        <p style="font-family: arial">If you are receiving this email and are not an employee of the Ministry of Education</p> 
                                        <p style="font-family: arial">please send an email to <a href="mailto:educwebs@victoria1.gov.bc.ca" style="color:#ff680d">Web Services</a>.</p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            <!-- </td>
        </tr>
    </table> -->', 'format' => 'full_html'],
    ]);

    $node->save();
}